import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './NavBar'
import "@radix-ui/themes/styles.css";
import { Container, Theme, ThemePanel } from "@radix-ui/themes";
import './theme-config.css'
import AuthProvider from './auth/AuthProvider';
import QueryClientProvider from './QueryClientProvider';


const inter = Inter({ 
  subsets: ['latin'],
  variable: "--font-inter",
 })

export const metadata: Metadata = {
  title: "Bhuvan's Issue Tracker",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <QueryClientProvider>
        <AuthProvider>
          <body className={inter.variable}>
            <Theme accentColor="sky" radius="full">
              <NavBar />
              <main className='p-5'> <Container>{children}</Container></main>
            </Theme>
            </body>
          </AuthProvider>
        </QueryClientProvider>
    </html>
  )
}
